name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install meson libglib2.0-dev libgudev-1.0-dev libjson-glib-dev libgtk-3-dev

      - name: Meson
        run: meson _build

      - name: Build
        run: meson compile -C _build
